### ISSUE TITLE
blam.sav - Gamepad rundown

### ISSUE THREAD

**Issue by BinToss** [Sigmmma/c20#101]
blam.sav Gamepad documentation is rather sparse right now.

The resolution of this Issue will answer the following questions:
- [ ] Q: _How many non-KB/M input devices can be assigned to a profile?_
    A: Four. The game does not allow any more to be assigned. Forcing it to do so may lead to an overflow of blam.sav 0x32A-0x339.

- [ ] Q: _How are the Menu Accept and Menu Back bindings able to share bindings with other controls, but not each other?_
    A: Two reasons. Unlike other bindings, Menu Accept and Menu Back are offsets with values (button enums) written to them. Secondly, these offsets are located in a range separate from the other bindings' offsets, as noted in the previous question's answer.

- [ ] Q: _How do I manipulate the file itself to assign bindings to Menu Accept and Menu Back for a specific gamepad in the profile?_
    A: GamePad 0's Menu Accept is written to 0x32A. Its Menu Back is 0x32C. GamePad 1's bindings start at 0x32E and so on.
        Like many values in blam.sav, these are stored as ~~Big-Endian~~ Little Endian—the last byte in a value is the first byte at the offset in the file and the first byte is at the end of the offset.

- [ ] Q: _How does the game know the difference between two identical input devices *in the file*? (how it does it in memory is another question altogether)_
    A: Two reasons. The first is the device name. When Halo detects two devices with the same name, the second one will have " (2)" appended to its name. Secondly, a boolean-type Byte is written after the string "PIDVID" in what I will call the "footer" of a gamepad entry. After the footer, there are three bytes of empty space before the header (and device name) of the next gamepad.

- [ ] Q: _Where are the gamepad bindings in the file?_
    A: The bindings for Gamepad 0 are scattered throughout blam.sav with the bindings for each gamepad following one another.
< a graph will be here later >
 
- [ ] Q: _Is any other gamepad data written to blam.sav?_
    A: As noted in previous question's answers, a gamepad's name/description, input bindings, Menu bindings, Product ID, Vendor ID, and duplicate-device bit are all written to blam.sav. 

Additional data is being collected and organized.

Edit 1: I inferred the meaning of Big Endian as the opposite of what it really is. I had the meanings of Big Endian and Little Endian mixed up these past few days and I only now realized it.

**Comment by BinToss** [comment]
Data Dump

Button 0 (usually A) can be found by the equation
0x22A + (0x40 * Gamepad#)
So Gamepad0's Button 0 would be at 0x22A
Gamepad1's would be 0x26A
Gamepad2's would be 0x2AA
Gamepad3's would be 0x2EA

Axis offsets would be 
inputOffset + (0x80 * GP#) starting with Gamepad0's Axis 1+ at 0x33A 

DPAD is
inputOffset + (0x100 * GP#)

MenuAccept/Back offsets are
0x32A + (0x4 * GP#)

Sensitivties are directly after Mouse sensitivities
```
      MouseSensitivityHorizontal = 0x0954,
      MouseSensitivityVertical   = 0x0955,
      GP0SensitivityHorizontal   = 0x0956,
      GP1SensitivityHorizontal   = 0x0957,
      GP2SensitivityHorizontal   = 0x0958,
      GP3SensitivityHorizontal   = 0x0959,
      GP0SensitivityVertical     = 0x095A,
      GP1SensitivityVertical     = 0x095B,
      GP2SensitivityVertical     = 0x095C,
      GP3SensitivityVertical     = 0x095D,
```

**Comment by csauve** [comment]
I've incorporated all of this into the page with the profile structure. It may take a day for the content to go live due to caching, but it's deployed now.
