### ISSUE TITLE
Update status of shaders/graphics in relation to MCC

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#112]
MCC now fully supports and correctly renders a lot of shaders and effects correctly, and the wiki currently still has them listed as broken.

shader transparent generic

shader environment (bumpmaps shadows render, specular tinting works and specular masking works on objects like scenery)
EDIT: some BSP triangles are dark for some reason.

shader model (detail after reflection works as it should)

atmospheric fog (sky fog)

planar fog with fog layers (fog tag)
EDIT: fog isn't rendering correctly over models as of season 7, appears to be some kind of depth issue.

shader plasma

**Comment by csauve** [comment]
I'm satisfied that MCC renderer fixes and known issues are documented.
