### ISSUE TITLE
Debug.txt entry for sapien crashes

### ISSUE THREAD

**Issue by Jakey757** [Sigmmma/c20#113]
`EXCEPTION halt in \halopc\haloce\source\tag_files\tag_groups.c,#3142: offset>=0 && offset+size<=data->size`

Some kind of tag corruption from HEK+ extraction. 

http://forum.halomaps.org/index.cfm?page=topic&topicID=38586
Monitor animations or a vehicle.

**Comment by csauve** [comment]
Documented in the HEK sapien page.
