### ISSUE TITLE
filthy part indexes

### ISSUE THREAD

**Issue by Jakey757** [Sigmmma/c20#120]
i might need some help with this one, i cant fully explain it. 
![image](https://user-images.githubusercontent.com/49990481/123432223-23f5f900-d598-11eb-814e-8069128b8d2b.png)
filthy part indexes can be used to change render order of transparent shaders. as far as i know only the needler fp.gbxmodel has them explicitly set in original tags.

through previous filthy part index you can set the part that will render before the current part. next filthy part sets the part that will render after the current part. -1 is a null value to not use an index, im not really sure what this does but it seems to be required. i wasnt able to figure out how to apply this to a model with only two parts, i had to create a new part for index 0 in needler ammo gbxmodel.

the fp needler model uses this to render the "core" over the glass, it also prevents a sorting issue that happens when transparent shaders are behind glass shaders that causes flickering when viewing at different angles.

**Comment by csauve** [comment]
We've gotten some info on this thanks to SnowyMouse. The index `0` is defaulting to `-1` when it shouldn't be, making it unusable. A more complete description will be merged into the wiki in the coming month or so.
