### ISSUE TITLE
BSP too large in size

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#121]
```
### ERROR vertex #0 has a bad point.
### ERROR failed to import collision bsp.
```

Tool error for bsp models exceeding a certain size (?) physically during compile.

http://forum.halomaps.org/index.cfm?page=topic&topicID=38314
https://discord.com/channels/228263208299790338/523620962390769695/859783266834579516 (reclaimers discord)

**Comment by csauve** [comment]
https://c20.reclaimers.net/h1/guides/level-creation/bsp-troubleshooting/
