### ISSUE TITLE
H3 Sapien - Missing information about debug menu

### ISSUE THREAD

**Issue by AKlinth** [Sigmmma/c20#126]
Hello, I wanted to give a tip about the debug menu in h3 Sapien. I don’t remember this being a feature in Halo CE, but I might be wrong since my knowledge is pretty limited. From what I can tell it is basically a more accessible and user-friendly way of executing commands.

Anyway, while looking at key binds for H3 Sapien, I noticed that there was no mention about a debug menu on the H3 Sapien page. The menu itself is pretty self-explanatory but it would be nice to see the key binds added to the page. The menu can be toggled by pressing <kbd>Home</kbd> and navigated using: <kbd>Up</kbd>, <kbd>Down</kbd>, <kbd>Enter</kbd> and <kbd>End</kbd>

I hope this information was helpful in some way.

![Skärmbild 2021-10-16 035745](https://user-images.githubusercontent.com/46730644/137569290-bcbc11aa-0e59-4884-a57b-2d87515d552b.png)

![image](https://user-images.githubusercontent.com/46730644/137569356-0dcb2dbf-eb5a-4278-bcd6-e0dee427cfc3.png)

**Comment by num0005** [comment]
#128

**Comment by gbMichelle** [comment]
Thank you for pointing this out to us! @num0005 took care of it and it's part of the wiki now.
