### ISSUE TITLE
HEK & H2V-EK aren't hyperlinked in "HEK with opensauce" & "H2V-EK with H2Codez"

### ISSUE THREAD

**Issue by ShellyHerself** [Sigmmma/c20#129]
![image](https://user-images.githubusercontent.com/24233409/137638071-9505d732-9971-45ad-aa4e-aa0fbb03897d.png)

**Comment by General-101** [comment]
Figured we didn't need to do this cause it's already linked before. Could add links for them anyways tho if you want them

**Comment by gbMichelle** [comment]
It would just be a bit cleaner. Because I personally did a double take where for a second I wasn't sure if we had pages for those.

I see a potential complication here: Opensauce's HEK has various additional tools in it.

**Comment by num0005** [comment]
what about just making the whole thing a link?
e.g. 
```markdown
[H2V-EK with H2Codez][h2codez]
```

**Comment by csauve** [comment]
I'm leaving the originally reported links the way they are. I don't think we need to duplicate the links and combining the rows is confusing because it kinda implies H2Codez or OpenSauce are _required_ which they aren't.
