### ISSUE TITLE
[Halo 1 Guides hub] - Missing tutorial links in the AI & Scripting section

### ISSUE THREAD

**Issue by num0005** [Sigmmma/c20#173]
I removed some tutorials with dead links, but that section has no links whatsoever. Is this intentional?

**Comment by num0005** [comment]
https://c20.reclaimers.net/h1/guides/#ai-and-scripting

**Comment by BinToss** [comment]
Have you tried using Archive.org for those dead links?

**Comment by csauve** [comment]
No longer an issue in the current wiki.
