### ISSUE TITLE
[Bug] "game.svg" missing on src/content/h1/readme.md

### ISSUE THREAD

**Issue by BinToss** [Sigmmma/c20#218]
Is it failing to render? The box art is still working fine, so maybe something is preventing the SVG from being processed.
Or was the file moved?

**Comment by BinToss** [comment]
Ah, the asset was change from a SVG to a DOT, but the reference wasn't updated.

https://github.com/Sigmmma/c20/blob/master/src/content/h1/games.dot

**Comment by csauve** [comment]
SVG rendering fixed in the last major update; the build container's node version wasn't compatible with the dot to SVG library we're using.
