### ISSUE TITLE
Solve page title collision problem

### ISSUE THREAD

**Issue by csauve** [Sigmmma/c20#23]
If content is added for H2 or other early Blam! games, there may be "collisions" between page titles especially for those related to common tag types. For example, a "shader" tag class page will probably exist for both Halo 1 and Halo 2. This could cause user confusion and make cross-page linking more verbose with the need to provide absolute paths for everything.

Some ways to deal with this are:

* Make editors use absolute paths in links to disambiguate (with either undefined behaviour or error at build time otherwise)
* Include h1 or h2 in the title of pages to disambiguate. Should it be done consistently for ALL Halo 1/2-related pages?
* Prefer link references within local page hierarchy, e.g. `[bitmap][]` links to H1 bitmap from the H1 shader page, and to H2 bitmap from the H2 shader page
* Link references are done via a fuzzy match so users can disambiguate without having to provide a full absolute path, e.g. `[biped][h1/biped]` matches `/h1/tags/object/unit/biped/`
* Game-specific page styling to help avoid user confusion (e.g. xbox h1, pc h1, cea, h2)
* Some combination of the above?

CoS;
* Decide on an approach with feedback from editors
* The approach is implemented unless too technically complex, in which case a spin-off ticket should be created

**Comment by gbMichelle** [comment]
I definitely think we should separate game folders. Potentially what can be done for shared info is some kind of an inheritance thing. Maybe this could potentially be done using header name references.

**Comment by csauve** [comment]
Having looked at our current markdown library, I think we can override how `reflink` is parsed and customize how it tries to resolve a successful linking:

https://github.com/markedjs/marked/blob/master/src/Tokenizer.js

For example, when someone links `[the scenario tag][scenario]` and we have both `h1/tags/scenario` and `/h2/tags/scenario`, I think it should pick the destination with the shortest path from the origin page. In cases where it's ambiguous or the editor wants to override that behaviour, we could support a syntax like `[the scenario tag][h2/tags/scenario]`. An advantage of overriding reflink parsing compared to the currently implementation is that we can also validate the destination and heading and fail the build for dead links rather than fall back to plain text like their code does.
