### ISSUE TITLE
The build is syncing ALL files not just modified ones

### ISSUE THREAD

**Issue by csauve** [Sigmmma/c20#70]
The `buildspec.yml` step to upload files to S3 was recently updated to:

```
aws s3 sync --delete --cache-control max-age=3600 --metadata-directive REPLACE ./dist s3://reclaimers-wiki-files
```

The `--cache-control max-age=3600` header is now being set at sync time on an object-by-object basis rather than at the CloudFront level because CloudFormation/CDK doesn't support defining it there. However, as a side-effect the sync now updates every file for every build and is eating up our monthly S3 free tier budget.

Research different flags for s3 sync or different ways to do the sync, or a different way to set cache TTL.

**Comment by csauve** [comment]
https://github.com/aws/aws-cdk/issues/9644

**Comment by gbMichelle** [comment]
I was going to suggest something dumb like `--size-only`. But if CloudFront now properly supports this it would be better to do it there.

**Comment by csauve** [comment]
Yeah we should be able to use this in our `reclaimers-aws` CDK code:
https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CachePolicy.html

**Comment by csauve** [comment]
I added the cache policy in reclaimers-aws during the c20 node upgrade.
