### ISSUE TITLE
Shader Model Self-Illumation doesn't affect True-Black colors.

### ISSUE THREAD

**Issue by VoidsShadow** [Sigmmma/c20#72]
![Self-Illumination Doesn't Affect True-Black](https://user-images.githubusercontent.com/7243190/95725242-4293aa00-0c2c-11eb-8539-2378c0fe3070.png)
![Near Black](https://user-images.githubusercontent.com/7243190/95725460-88e90900-0c2c-11eb-9d20-304d17877d3c.png)
![True Black](https://user-images.githubusercontent.com/7243190/95725501-98685200-0c2c-11eb-9d67-d801b75b27c0.png)

**Comment by Lolibox** [comment]
by the shader model description of self illumination i just assumed the color was added to the diffuse color also, but what it was literally saying is it **adds to diffuse light** the self illumination color is multiplied by the diffuse color and then added to model lighting. 

thanks for posting this, hopefully its useful.
