### ISSUE TITLE
Actor variant

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#73]
### Flags
On/off toggles for various things

**Can shoot while flying**
**Interpolate color in HSV** interpolates between the change color bounds along hue saturation value
**Has unlimited grenades** when enabled gives the actor unlimited grenades
**Moveswitch stay w/friends**
**Active camouflage** when enabled gives the actor permanent camo comparable to player camo
**Super active camouflage** when enabled makes the active camo the "hyper stealth" variant in globals
**Cannot use ranged weapon**s when enabled disables ranged combat settings
**Prefer passenger seat** when enabled will make the actor choose a passenger seat if one is available over a gunner seat

### References
Misc tag references

**Actor definition** specifies which actor tag to use
**Unit** is what biped this variant will spawn as
**Major variant** determines the major variant this one can upgrade into

### Movement switching
clueless about this at the moment

### Ranged combat
Defines how actors use their weapon

**Weapon** is the referenced weapon the actor spawns with
**Maximum firing distance** is how far the actor can fire from in world units
**Rate of fire** lets you select a rof value within the weapons maximum rate of fire, 0 uses the weapons maximum
**Projectile error** adds error ontop of the weapons defined error
**First burst delay time** is the delay in seconds before the actor starts its first burst on a new target
**New-target firing pattern time**
**Surprise delay time**
**Surprise fire-wildly time**
**Death fire-wildly chance** 
**Death fire-wildly time** 
**Desired combat range** is the distance in world units the actor will try to be in to attack, lower bounds is the minimum range and upper is the maximum
**Custom stand gun offset**
**Custom crouch gun offset**
**Target tracking** is how closely the actor will follow moving targets. 0=not following at all and shooting at the targets last location before it moved, 1=following the target perfectly. interpolates everything in between
**Target leading** is how accurately to predict lead on moving targets. 0=not leading at all and shooting directly at the target, 1=perfectly predicting how far in front of the target to lead based on projectile speed and distance. interpolates everything in between
**Weapon damage modifier** is a multiplier on the weapons damage
**Damage per second** overrides weapon damage if set and weapon damage modifier is 0

### Burst geometry
Controls burst properties

**Burst origin radius** is the starting point of the burst randomly from the left or right of the target in world units
**Burst origin angle** is the angle from the horizontal the burst starts
**Burst return length** is how far the burst moves back toward the target in world units. chosen randomly between the two bounds. 
**Burst return angle** is the angle from the horizontal the return burst ends at
**Burst duration** is the length of the burst in seconds. chosen randomly between the two bounds.
**Burst separation** is the time to wait between starting a new burst
**Burst angular velocity** caps the speed on the return burst in degrees/s? effectively shortens the burst origin distance.

The burst origin and duration control how fast the return burst is. If the origin radius is large and the duration is short, the return burst will cover a large area in a short amount of time. 

If the burst origin radius is non 0 and the return length is larger than the burst origin radius it will move past the target, and if shorter it will undershoot the target. Negative values can be used to move the return burst in the opposite direction.

### Firing patterns
Multipliers to burst geometry and ranged combat settings depending on actors current state

**New-target** is when the actor finds a new target to shoot at
**Moving** is when the actor is moving between firing points while shooting
**Berserk** is when the actor is in a berserk state

### Special-case firing properties
Actor charge fire or secondary trigger settings

**Special damage modifier** is a multiplier on special fire damage*
**Special projectile error** is error added ontop of the weapons error for special fire*
moved here from burst geometry because it didnt make sense for it to be there*

### Berserking and melee
Ranges for berserk and melee in world units

**Melee range** is the minimum distance an actor will attempt to melee an enemy
**Melee abort range** is the distance an actor will give up on trying to melee an enemy once attempting to melee
**Berserk firing ranges** is the desired combat range for shooting while berserked
**Berserk melee range** is the minimum distance a berserked actor will attempt to melee an enemy
**Berserk melee abort range** is the distance a berserked actor will give up on trying to melee an enemy once attempting to melee

### Grenades
Grenade settings 

**Grenade type**
**Trajectory type**

### Items
Controls what the actor drops on death

**Equipment** references the equipment tag the actor drops on death
**Grenade count** is how many grenades the actor drops on death, random range between the two bounds
**Dont drop grenades chance** is the percent chance the actor doesn't drop any grenades on death. 0=0% 1=100%
**Drop weapon loaded** is the percentage of the magazine/battery left in the weapon the actor drops on death, in a random range between the two bounds
**Drop weapon ammo** is the total reserve ammo the weapon can have when dropped, random range between the two bounds

### Unit
Misc biped settings

**Body vitality** sets the actors body health
**Shield vitality** sets the actors shield strength
**Shield sapping radius**
**Forced shader permutation** forces the bitmap index for any shader the biped uses. ex: the grouped elite cubemaps
**Change colors** overrides the bipeds color change permutations

**Comment by csauve** [comment]
Changes made in https://github.com/Sigmmma/c20/pull/76
