### ISSUE TITLE
Sapien shortcuts

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#75]
Apparently there are some useful shortcut keys to activate commands/features in sapien

http://forum.halomaps.org/index.cfm?page=topic&topicID=45792

http://forum.halomaps.org/index.cfm?page=topic&topicID=49013

juicy frank mentions somebody may have poked around in sapiens executable to find some of them

make sure the game window in sapien is **highlighted** then press v+m
![sapien_MMGnNDyXb5](https://user-images.githubusercontent.com/49990481/97374207-30517700-188e-11eb-8a27-bd83c49243b8.png)

**Comment by Lolibox** [comment]
V+N hides editor icons and name overlays, doesnt seem to be a toggle, resets when sapien is restarted.

**Comment by Lolibox** [comment]
If V+M is used, on next sapien load some object names are shown, looks like devices. Currently dont know how to toggle them aside from resetting the sapien config or V+N. V+M also highlights editor gizmo's making them easier to see.

**Comment by csauve** [comment]
Apparently you just need to press M (without V) to get the firing position labels.
