### ISSUE TITLE
Active camouflage globals

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#82]
globals.globals tag, rasterizer block, active camo sub

![pythonw_5TbkZ3E3at](https://user-images.githubusercontent.com/49990481/98145176-c0984900-1e98-11eb-81d7-295cdda09af8.png)

tint edge density flag
adds the tint color to the background

refraction amount
how much to distort the background, lower values distort more, higher distorts less. measured in pixels?

distance falloff
the distance in world units the active camo effect fades completely and the object is entirely invisible

tint color
color multiplied over the background

hyper stealth values
same as above but used when "super active camo" flag is enabled in an actor variant

extra: the alpha channel in the active camo texture masks the tint colors on PC

**Comment by gbMichelle** [comment]
Refraction amount is definitely not pixels
(Both pics have LODs forced the highest to avoid lod normals making our results differ)
1280x960
![haloce_2020-11-08_05-38-32-790](https://user-images.githubusercontent.com/24233409/98457126-f3865980-2184-11eb-897a-6e3c68ffde13.jpg)
640x480
![haloce_2020-11-08_05-38-04-961](https://user-images.githubusercontent.com/24233409/98457128-fbde9480-2184-11eb-9d32-28fcc22ee712.png)

Switch these two images back to back and you will see the refraction is identical.
I will be removing the part where it says pixels in the mozz. And adding wu for world units on the falloffs

**Comment by gbMichelle** [comment]
The way the colors work is indeed multiply. Setting it to 1 1 1 will cause no visible change. 0 0 0 causes pitch black.
