### ISSUE TITLE
sound_looping wiki submission - Halo / Sapien limits max snds per class / affected by snd quality setting and possibly total tag size

### ISSUE THREAD

**Issue by neonspider** [Sigmmma/c20#92]
![image](https://user-images.githubusercontent.com/3197704/105796109-fa3da380-5ff2-11eb-8fae-1bdd6fe95676.png)

Having a sound_looping with multiple simultaneous layers for a portalled background sound it seems to be that the engine will only visibly play back the first two ambient_nature sounds in a list. Any further sounds will not be heard.

**Comment by gbMichelle** [comment]
Any more specifics in the tag setup like skip fractions?

**Comment by neonspider** [comment]
> 
> 
> Any more specifics in the tag setup like skip fractions?

No skip fractions or any random elements are a part of these current tags, though they are split into shorter permutations to avoid the long ogg bug. Seems to also occur with xbox-adpcm when also split, haven't tried .wav

It seems like each of the ambient and device classes have separate "polyphonies" so to speak, so you can have two ambient_natures and one ambient_computers, but not three ambient_natures.

**Comment by csauve** [comment]
Do you know if each of those "polyphonies" is limited to 2? e.g. ambient_computers has a max of 2 as well?

**Comment by neonspider** [comment]
Will investigate and get back to you, but my theory would that the non nature ambient sounds (machinery, computers) are likely limited to a single voice or similarly two at the most, with the intention of "sound priority" for on the original xbox, so for example, if an ambient computer sound is playing, maybe a device computer sound on xbox wouldn't have played if no additional voices were available or something like that.

Gonna try to find a multiplayer map with a lot of portals quickly accessible by foot so I can easier test this, since I can't map for myself :P

**Comment by neonspider** [comment]
New finding.

I create voicelines for a few of the different sound classes that play sounds one after the other (two for each class) but are all separate sound files.

My findings so far seem to be that four ambient_natures did seem to play just find, however a sound quality of medium cut off at three simultaneous sounds of the same class, and low cut off at just two. It's possible that the amount of simultaneous voices could perhaps be relative to the game sound settings, and available memory or the size of sound tags? These test sounds are 44.1khz stereo ogg-vorbis tags with no split permutations and 0.4 compression quality (about 140kbps) with invader-sound and tool both tested to compile/ Total size of test sound tags only takes up about 1.1MB.

**Comment by neonspider** [comment]
Alrighty!

It looks like I jumped the gun on sending this, it's not that the game necessarily limits to two (it is four), but Sapien limits to two of every sound class, I think. This could be a holdover from Xbox or potentially Sapien just internally runs at the equivalent of all medium settings in Halo?
